#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=dftri_train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=output/DFTRI_output%A_%a.out
#SBATCH --array=0-3

set -e

source $HOME/miniconda3/start1260.sh
conda activate triangle_splatting

cd $HOME/df-triangle-splatting

# Map array index -> scene
SCENES=(garden bicycle kitchen bonsai)
SCENE=${SCENES[$SLURM_ARRAY_TASK_ID]}

echo "Training scene: $SCENE"

python train.py \
    -s $HOME/mipnerf/$SCENE \
    -m output/m360/$SCENE \
    --iterations 30000 \
    --depth_ratio 0.5 \
    --densify_error_beta 3.0 \
    --densify_normal_beta 3.0 \
    --split_normal_threshold 0.5 \
    --lambda_normals 0 \
    --outdoor