#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=dftri_depth
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=output/ranges_%A_%a.out
#SBATCH --array=0-3

set -e
source $HOME/miniconda3/start1260.sh
conda activate triangle_splatting
(
    cd $HOME/df-triangle-splatting

    # rebuild
    # pushd submodules/diff-triangle-rasterization/
    # pip install --no-build-isolation --upgrade .
    # popd
    # echo -e "\nFinished building, starting training.\n"

    ITERATIONS=30000
    SCENES=(counter005 garden005 kitchen005 room005)
    SCENE=${SCENES[$SLURM_ARRAY_TASK_ID]}

    #  bicycle kitchen bonsai

    MODEL=output/m360_seed_growth_array/${SCENE}
    python render_depth_ranges.py -m $MODEL --iteration $ITERATIONS

)
