#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=dftri_train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:10:00
#SBATCH --output=output/DFTRI_output%A.out

set -e
source $HOME/miniconda3/start1260.sh
conda activate triangle_splatting
(
    cd $HOME/df-triangle-splatting

    # rebuild
    pushd submodules/diff-triangle-rasterization/
    pip install --no-build-isolation --upgrade .
    popd
)