#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=dftri_train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=02:00:00
#SBATCH --output=output/DFTRI_output%A.out

source $HOME/miniconda3/start1260.sh
conda activate triangle_splatting
(
    cd $HOME/df-triangle-splatting
    SCENE="bicycle"
    python train.py -s $HOME/mipnerf/$SCENE -m output/m360/$SCENE --iterations 5000
    python render.py -m output/m360/$SCENE --quick
)